INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 5, 'Unit 5', 'Vocabulary Unit 5', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 5);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 6, 'Unit 6', 'Vocabulary Unit 6', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 6);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 7, 'Unit 7', 'Vocabulary Unit 7', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 7);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 8, 'Unit 8', 'Vocabulary Unit 8', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 8);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 9, 'Unit 9', 'Vocabulary Unit 9', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 9);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 10, 'Unit 10', 'Vocabulary Unit 10', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 10);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 11, 'Unit 11', 'Vocabulary Unit 11', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 11);
INSERT INTO units (id, title, description, order_index, created_at, updated_at) SELECT 12, 'Unit 12', 'Vocabulary Unit 12', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM units WHERE id = 12);



INSERT INTO vocabularies (unit_id, kanji, hiragana, romaji, meaning, sino_vietnamese, example_sentence, created_at, updated_at) VALUES 
(5, '', 'いらいら', '', 'Sốt ruột, bực dọc', '', '', NOW(), NOW()),
(5, '', 'のんびり', '', 'Thong thả, thong dong', '', '', NOW(), NOW()),
(5, '実は', 'じつは', '', 'Thực ra thì', 'Thực', '', NOW(), NOW()),
(5, '読書', 'どくしょ', '', 'Đọc sách', 'Độc Thư', '', NOW(), NOW()),
(5, '演奏', 'えんそう', '', 'Biểu diễn (nhạc cụ)', 'Diễn Tấu', '', NOW(), NOW()),
(5, '芸術', 'げいじゅつ', '', 'Nghệ thuật', 'Nghệ Thuật', '', NOW(), NOW()),
(5, '検査', 'けんさ', '', 'Kiểm tra (y tế, kỹ thuật)', 'Kiểm Tra', '', NOW(), NOW()),
(5, '血液', 'けつえき', '', 'Máu', 'Huyết Dịch', '', NOW(), NOW()),
(5, '治療', 'ちりょう', '', 'Điều trị, trị liệu', 'Trị Liệu', '', NOW(), NOW()),
(5, '症状', 'しょうじょう', '', 'Triệu chứng', 'Chứng Trạng', '', NOW(), NOW()),
(5, '予防', 'よぼう', '', 'Phòng ngừa', 'Dự Phòng', '', NOW(), NOW()),
(5, '栄養', 'えいよう', '', 'Dinh dưỡng', 'Vinh Dưỡng', '', NOW(), NOW()),
(5, '手術', 'しゅじゅつ', '', 'Phẫu thuật', 'Thủ Thuật', '', NOW(), NOW()),
(5, '死亡', 'しぼう', '', 'Tử vong', 'Tử Vong', '', NOW(), NOW()),
(5, '命', 'いのち', '', 'Sinh mạng, cuộc đời', 'Mệnh', '', NOW(), NOW()),
(5, '一生', 'いっしょう', '', 'Cả đời', 'Nhất Sinh', '', NOW(), NOW()),
(5, '誤解', 'ごかい', '', 'Hiểu lầm', 'Ngộ Giải', '', NOW(), NOW()),
(5, '後悔', 'こうかい', '', 'Hối hận', 'Hậu Hối', '', NOW(), NOW()),
(5, '訳', 'わけ', '', 'Lý do, nguyên nhân', 'Dịch', '', NOW(), NOW()),
(5, '態度', 'たいど', '', 'Thái độ', 'Thái Độ', '', NOW(), NOW()),
(5, '癖', 'くせ', '', 'Thói quen, tật', 'Phích', '', NOW(), NOW()),
(5, '礼儀', 'れいぎ', '', 'Lễ nghi, phép lịch sự', 'Lễ Nghi', '', NOW(), NOW()),
(5, '文句', 'もんく', '', 'Phàn nàn, cãi lại', 'Văn Cú', '', NOW(), NOW()),
(5, '表情', 'ひょうじょう', '', 'Biểu cảm khuôn mặt', 'Biểu Tình', '', NOW(), NOW()),
(5, '表面', 'ひょうめん', '', 'Bề mặt', 'Biểu Diện', '', NOW(), NOW()),
(5, '禁煙', 'きんえん', '', 'Cấm hút thuốc', 'Cấm Yên', '', NOW(), NOW()),
(5, '禁止', 'きんし', '', 'Cấm, nghiêm cấm', 'Cấm Chỉ', '', NOW(), NOW()),
(5, '完成', 'かんせい', '', 'Hoàn thành', 'Hoàn Thành', '', NOW(), NOW()),
(5, '課題', 'かだい', '', 'Vấn đề, bài tập', 'Khóa Đề', '', NOW(), NOW()),
(5, '例外', 'れいがい', '', 'Ngoại lệ', 'Lệ Ngoại', '', NOW(), NOW()),
(5, '基本', 'きほん', '', 'Cơ bản', 'Cơ Bản', '', NOW(), NOW()),
(5, '記録', 'きろく', '', 'Ghi chép, kỷ lục', 'Ký Lục', '', NOW(), NOW()),
(5, '状態', 'じょうたい', '', 'Trạng thái', 'Trạng Thái', '', NOW(), NOW()),
(5, '出来事', 'できごと', '', 'Sự kiện, việc xảy ra', 'Xuất Lai Sự', '', NOW(), NOW()),
(5, '場面', 'ばめん', '', 'Tình huống, bối cảnh', 'Tràng Diện', '', NOW(), NOW()),
(5, '機会', 'きかい', '', 'Cơ hội', 'Cơ Hội', '', NOW(), NOW()),
(5, '距離', 'きょり', '', 'Khoảng cách', 'Cự Ly', '', NOW(), NOW()),
(5, '提案', 'ていあん', '', 'Đề xuất', 'Đề Án', '', NOW(), NOW()),
(5, 'やり取り', 'やりとり', '', 'Trao đổi, qua lại', '-', '', NOW(), NOW()),
(5, '知識', 'ちしき', '', 'Kiến thức', 'Tri Thức', '', NOW(), NOW()),
(5, '実力', 'じつりょく', '', 'Thực lực', 'Thực Lực', '', NOW(), NOW()),
(5, '手段', 'しゅだん', '', 'Phương tiện, cách thức', 'Thủ Đoạn', '', NOW(), NOW()),
(5, '代表', 'だいひょう', '', 'Đại diện', 'Đại Biểu', '', NOW(), NOW()),
(5, '影響', 'えいきょう', '', 'Ảnh hưởng', 'Ảnh Hưởng', '', NOW(), NOW()),
(5, '効果', 'こうか', '', 'Hiệu quả', 'Hiệu Quả', '', NOW(), NOW()),
(5, '印象', 'いんしょう', '', 'Ấn tượng', 'Ấn Tượng', '', NOW(), NOW()),
(5, '印', 'しるし', '', 'Dấu hiệu, dấu vết', 'Ấn', '', NOW(), NOW()),
(5, '合図', 'あいず', '', 'Ra hiệu, ám hiệu', 'Hợp Đồ', '', NOW(), NOW()),
(5, '共通', 'きょうつう', '', 'Điểm chung', 'Cộng Thông', '', NOW(), NOW()),
(5, '強調', 'きょうちょう', '', 'Nhấn mạnh', 'Cường Điều', '', NOW(), NOW()),
(5, '省略', 'しょうりゃく', '', 'Lược bỏ', 'Tỉnh Lược', '', NOW(), NOW()),
(5, '挑戦', 'ちょうせん', '', 'Thử thách', 'Khiêu Chiến', '', NOW(), NOW()),
(5, 'やる気', 'やるき', '', 'Động lực, quyết tâm', 'Khí', '', NOW(), NOW()),
(5, '勇気', 'ゆうき', '', 'Dũng cảm', 'Dũng Khí', '', NOW(), NOW()),
(5, '資格', 'しかく', '', 'Bằng cấp, tư cách', 'Tư Cách', '', NOW(), NOW()),
(5, '申請', 'しんせい', '', 'Đăng ký, xin cấp', 'Thân Thỉnh', '', NOW(), NOW()),
(5, '本人', 'ほんにん', '', 'Bản thân (người đó)', 'Bản Nhân', '', NOW(), NOW()),
(5, '契約', 'けいやく', '', 'Hợp đồng', 'Khế Ước', '', NOW(), NOW()),
(5, '証明', 'しょうめい', '', 'Chứng minh', 'Chứng Minh', '', NOW(), NOW()),
(5, '変更', 'へんこう', '', 'Thay đổi', 'Biến Canh', '', NOW(), NOW()),
(5, '保存', 'ほぞん', '', 'Lưu lại, bảo quản', 'Bảo Tồn', '', NOW(), NOW()),
(5, '保護', 'ほご', '', 'Bảo vệ (môi trường, cá nhân)', 'Bảo Hộ', '', NOW(), NOW()),
(5, '環境', 'かんきょう', '', 'Môi trường', 'Hoàn Cảnh', '', NOW(), NOW()),
(5, '資源', 'しげん', '', 'Tài nguyên', 'Tư Nguyên', '', NOW(), NOW()),
(5, '不足', 'ふそく', '', 'Thiếu hụt', 'Bất Túc', '', NOW(), NOW()),
(5, '平均', 'へいきん', '', 'Trung bình', 'Bình Quân', '', NOW(), NOW()),
(5, '割合', 'わりあい', '', 'Tỷ lệ', 'Cát Hợp', '', NOW(), NOW()),
(5, '商売', 'しょうばい', '', 'Kinh doanh, buôn bán', 'Thương Mại', '', NOW(), NOW()),
(5, '商品', 'しょうひん', '', 'Hàng hóa, sản phẩm', 'Thương Phẩm', '', NOW(), NOW()),
(5, '質', 'しつ', '', 'Chất lượng', 'Chất', '', NOW(), NOW()),
(5, '型', 'かた', '', 'Kiểu, mẫu', 'Hình', '', NOW(), NOW()),
(5, '生産', 'せいさん', '', 'Sản xuất', 'Sinh Sản', '', NOW(), NOW()),
(5, '消費', 'しょうひ', '', 'Tiêu dùng', 'Tiêu Phí', '', NOW(), NOW()),
(5, '物価', 'ぶっか', '', 'Giá cả', 'Vật Giá', '', NOW(), NOW()),
(5, '倒産', 'とうさん', '', 'Phá sản', 'Đảo Sản', '', NOW(), NOW()),
(5, '携帯', 'けいたい', '', 'Mang theo, di động', 'Huề Đới', '', NOW(), NOW()),
(5, '現代', 'げんだい', '', 'Hiện đại', 'Hiện Đại', '', NOW(), NOW()),
(5, '世紀', 'せいき', '', 'Thế kỷ', 'Thế Kỷ', '', NOW(), NOW()),
(5, '文化', 'ぶんか', '', 'Văn hóa', 'Văn Hóa', '', NOW(), NOW()),
(5, '都市', 'とし', '', 'Đô thị', 'Đô Thị', '', NOW(), NOW()),
(5, '地方', 'ちほう', '', 'Địa phương', 'Địa Phương', '', NOW(), NOW()),
(5, '戦争', 'せんそう', '', 'Chiến tranh', 'Chiến Tranh', '', NOW(), NOW()),
(5, '平和', 'へいわ', '', 'Hòa bình', 'Bình Hòa', '', NOW(), NOW());


INSERT INTO vocabularies (unit_id, kanji, hiragana, romaji, meaning, sino_vietnamese, example_sentence, created_at, updated_at) VALUES 
-- Unit 6
(6, '上る', 'のぼる', '', 'Leo lên, tăng lên', 'Thượng', '', NOW(), NOW()),
(6, '下る', 'くだる', '', 'Đi xuống, hạ xuống', 'Hạ', '', NOW(), NOW()),
(6, '進む', 'すすむ', '', 'Tiến lên, tiến triển', 'Tiến', '', NOW(), NOW()),
(6, '進める', 'すすめる', '', 'Thúc đẩy, tiến hành', 'Tiến', '', NOW(), NOW()),
(6, '通る', 'とおる', '', 'Đi qua, đỗ (kỳ thi)', 'Thông', '', NOW(), NOW()),
(6, '通す', 'とおす', '', 'Cho đi qua, xuyên qua', 'Thông', '', NOW(), NOW()),
(6, '超える・越える', 'こえる', '', 'Vượt qua', 'Siêu / Việt', '', NOW(), NOW()),
(6, '過ぎる', 'すぎる', '', 'Quá, đi qua', 'Quá', '', NOW(), NOW()),
(6, '過ごす', 'すごす', '', 'Trải qua, dành (thời gian)', 'Quá', '', NOW(), NOW()),
(6, '移る', 'うつる', '', 'Chuyển sang, lây nhiễm', 'Di', '', NOW(), NOW()),
(6, '移す', 'うつす', '', 'Di chuyển, lây bệnh', 'Di', '', NOW(), NOW()),
(6, '連れる', 'つれる', '', 'Dẫn đi cùng', 'Liên', '', NOW(), NOW()),
(6, '寄る', 'よる', '', 'Ghé vào', 'Ký', '', NOW(), NOW()),
(6, '寄せる', 'よせる', '', 'Ghé sát vào, áp lại', 'Ký', '', NOW(), NOW()),
(6, '与える', 'あたえる', '', 'Cho, cung cấp, gây ra', 'Dữ', '', NOW(), NOW()),
(6, '得る', 'える', '', 'Đạt được, thu được', 'Đắc', '', NOW(), NOW()),
(6, '向く', 'むく', '', 'Hướng về, phù hợp', 'Hướng', '', NOW(), NOW()),
(6, '向ける', 'むける', '', 'Chĩa về, hướng về phía', 'Hướng', '', NOW(), NOW()),
(6, '勧める', 'すすめる', '', 'Khuyên bảo, gợi ý', 'Khuyến', '', NOW(), NOW()),
(6, '薦める', 'すすめる', '', 'Tiến cử, giới thiệu', 'Tiến', '', NOW(), NOW()),
(6, '任せる', 'まかせる', '', 'Giao phó, phó thác', 'Nhậm', '', NOW(), NOW()),
(6, '守る', 'まもる', '', 'Bảo vệ, tuân thủ', 'Thủ', '', NOW(), NOW()),
(6, '争う', 'あらそう', '', 'Cạnh tranh, cãi vã', 'Tranh', '', NOW(), NOW()),
(6, '望む', 'のぞむ', '', 'Mong muốn, hy vọng', 'Vọng', '', NOW(), NOW()),
(6, '信じる', 'しんじる', '', 'Tin tưởng', 'Tín', '', NOW(), NOW()),
(6, '通じる', 'つうじる', '', 'Hiểu, thông suốt', 'Thông', '', NOW(), NOW()),
(6, '飽きる', 'あきる', '', 'Chán ngấy', 'Bão', '', NOW(), NOW()),
(6, '思いつく', 'おもいつく', '', 'Nảy ra ý tưởng', 'Tư', '', NOW(), NOW()),
(6, '思いやる', 'おもいやる', '', 'Quan tâm, thông cảm', 'Tư', '', NOW(), NOW()),
(6, '熱中する', 'ねっちゅうする', '', 'Say sưa, mải mê', 'Nhiệt Trung', '', NOW(), NOW()),
(6, '暮らす', 'くらす', '', 'Sống, sinh hoạt', 'Mộ', '', NOW(), NOW()),
(6, '巻く', 'まく', '', 'Cuốn, quấn, bọc', 'Quyển', '', NOW(), NOW()),
(6, '結ぶ', 'むすぶ', '', 'Buộc, nối', 'Kết', '', NOW(), NOW()),
(6, '済む', 'すむ', '', 'Kết thúc, xong xuôi', 'Tế', '', NOW(), NOW()),
(6, '済ませる', 'すませる', '', 'Hoàn thành, làm xong', 'Tế', '', NOW(), NOW()),
(6, '出来る', 'できる', '', 'Hoàn thành, có thể', 'Xuất Lai', '', NOW(), NOW()),
(6, '切れる', 'きれる', '', 'Bị đứt, hết hạn/hết hàng', 'Thiết', '', NOW(), NOW()),
(6, '切らす', 'きらす', '', 'Dùng hết', 'Thiết', '', NOW(), NOW()),
(6, '伝わる', 'つたわる', '', 'Được truyền đi', 'Truyền', '', NOW(), NOW()),
(6, '伝える', 'つたえる', '', 'Truyền đạt, báo lại', 'Truyền', '', NOW(), NOW()),
(6, '続く', 'つづく', '', 'Tiếp tục, kéo dài', 'Tục', '', NOW(), NOW()),
(6, '続ける', 'つづける', '', 'Tiếp tục (làm gì đó)', 'Tục', '', NOW(), NOW()),
(6, 'つながる', 'つながる', '', 'Được kết nối, liên quan', '', '', NOW(), NOW()),
(6, 'つなぐ', 'つなぐ', '', 'Nối, buộc vào', '', '', NOW(), NOW()),
(6, 'つなげる', 'つなげる', '', 'Kết nối', '', '', NOW(), NOW()),
(6, '伸びる', 'のびる', '', 'Dài ra, lớn lên, tăng', 'Thân', '', NOW(), NOW()),
(6, '伸ばす', 'のばす', '', 'Làm dài ra, phát triển', 'Thân', '', NOW(), NOW()),
(6, '延びる', 'のびる', '', 'Trì hoãn, kéo dài (thời gian)', 'Diên', '', NOW(), NOW()),
(6, '延ばす', 'のばす', '', 'Trì hoãn', 'Diên', '', NOW(), NOW()),
(6, '重なる', 'かさなる', '', 'Chồng chất, trùng lặp', 'Trọng', '', NOW(), NOW()),
(6, '重ねる', 'かさねる', '', 'Xếp chồng lên', 'Trọng', '', NOW(), NOW()),
(6, '広がる', 'ひろがる', '', 'Lan rộng, mở rộng', 'Quảng', '', NOW(), NOW()),
(6, '広げる', 'ひろげる', '', 'Làm rộng ra', 'Quảng', '', NOW(), NOW()),
(6, '載る', 'のる', '', 'Được đăng tải, được đặt lên', 'Tái', '', NOW(), NOW()),
(6, '載せる', 'のせる', '', 'Đăng lên, chất lên', 'Tái', '', NOW(), NOW()),
(6, 'そろう', 'そろう', '', 'Tập hợp đầy đủ', '', '', NOW(), NOW()),
(6, 'そろえる', 'そろえる', '', 'Chuẩn bị đầy đủ, sắp xếp', '', '', NOW(), NOW()),
(6, 'まとまる', 'まとまる', '', 'Được thống nhất, tổng hợp', '', '', NOW(), NOW()),
(6, 'まとめる', 'まとめる', '', 'Tóm tắt, thu thập lại', '', '', NOW(), NOW()),
(6, '付く', 'つく', '', 'Dính, đính kèm, có', 'Phó', '', NOW(), NOW()),
(6, '付ける', 'つける', '', 'Bôi, gắn, dính vào', 'Phó', '', NOW(), NOW()),
(6, 'たまる', 'たまる', '', 'Ứ đọng, tích tụ', '', '', NOW(), NOW()),
(6, 'ためる', 'ためる', '', 'Tích trữ, tiết kiệm', '', '', NOW(), NOW()),
(6, '混じる', 'まじる', '', 'Bị lẫn vào', 'Hỗn', '', NOW(), NOW()),
(6, '混ざる', 'まざる', '', 'Hòa trộn với nhau', 'Hỗn', '', NOW(), NOW()),
(6, '混ぜる', 'まぜる', '', 'Trộn, khuấy', 'Hỗn', '', NOW(), NOW()),
(6, '解ける・溶ける', 'とける', '', 'Tan, được giải quyết', 'Giải / Dung', '', NOW(), NOW()),
(6, '解く・溶かす', 'とく・とかす', '', 'Giải quyết, làm tan', 'Giải / Dung', '', NOW(), NOW()),
(6, '含む', 'ふくむ', '', 'Bao gồm, chứa đựng', 'Hàm', '', NOW(), NOW()),
(6, '含める', 'ふくめる', '', 'Gộp vào, bao gồm', 'Hàm', '', NOW(), NOW()),
(6, '抜ける', 'ぬける', '', 'Bị rụng, bị tuột, thoát khỏi', 'Bạt', '', NOW(), NOW()),
(6, '抜く', 'ぬく', '', 'Nhổ, rút, bỏ bớt', 'Bạt', '', NOW(), NOW()),
(6, '現れる', 'あらわれる', '', 'Xuất hiện, lộ diện', 'Hiện', '', NOW(), NOW()),
(6, '現す', 'あらわす', '', 'Làm xuất hiện, thể hiện', 'Hiện', '', NOW(), NOW()),
(6, '表れる', 'あらわれる', '', 'Biểu hiện ra (trên mặt/văn)', 'Biểu', '', NOW(), NOW()),
(6, '表す', 'あらわす', '', 'Thể hiện, biểu đạt', 'Biểu', '', NOW(), NOW()),
(6, '散る', 'ちる', '', 'Rơi, rụng', 'Tán', '', NOW(), NOW()),
(6, '散らす', 'ちらす', '', 'Làm cho rụng, phân tán', 'Tán', '', NOW(), NOW()),
(6, '明ける', 'あける', '', 'Mở ra, rạng (sáng), hết (năm)', 'Minh', '', NOW(), NOW()),
(6, '差す', 'さす', '', 'Che (ô), chiếu (nắng)', 'Sai', '', NOW(), NOW()),

-- Unit 7
(7, '', 'パートナー', '', 'Đối tác, người cộng sự', '', '', NOW(), NOW()),
(7, '', 'リーダー', '', 'Lãnh đạo, trưởng nhóm', '', '', NOW(), NOW()),
(7, '', 'ボランティア', '', 'Tình nguyện viên', '', '', NOW(), NOW()),
(7, '', 'コミュニケーション', '', 'Giao tiếp', '', '', NOW(), NOW()),
(7, '', 'ユーモア', '', 'Hài hước', '', '', NOW(), NOW()),
(7, '', 'ショック', '', 'Cú sốc', '', '', NOW(), NOW()),
(7, '', 'ストレス', '', 'Căng thẳng', '', '', NOW(), NOW()),
(7, '', 'バランス', '', 'Sự cân bằng', '', '', NOW(), NOW()),
(7, '', 'レベル', '', 'Cấp độ, trình độ', '', '', NOW(), NOW()),
(7, '', 'アップ', '', 'Sự tăng lên, nâng cao', '', '', NOW(), NOW()),
(7, '', 'ダウン', '', 'Giảm xuống, đi xuống', '', '', NOW(), NOW()),
(7, '', 'プラス', '', 'Điểm cộng, dấu cộng', '', '', NOW(), NOW()),
(7, '', 'マイナス', '', 'Điểm trừ, dấu trừ', '', '', NOW(), NOW()),
(7, '', 'イメージ', '', 'Hình ảnh, ấn tượng', '', '', NOW(), NOW()),
(7, '', 'コンテスト', '', 'Cuộc thi', '', '', NOW(), NOW()),
(7, '', 'マスコミ', '', 'Phương tiện truyền thông', '', '', NOW(), NOW()),
(7, '', 'プライバシー', '', 'Quyền riêng tư', '', '', NOW(), NOW()),
(7, '', 'オフィス', '', 'Văn phòng làm việc', '', '', NOW(), NOW()),
(7, '', 'ルール', '', 'Quy tắc, luật lệ', '', '', NOW(), NOW()),
(7, '', 'マナー', '', 'Phép lịch sự, quy tắc ứng xử', '', '', NOW(), NOW()),
(7, '', 'ミス', '', 'Lỗi sai', '', '', NOW(), NOW()),
(7, '', 'スケジュール', '', 'Lịch trình, thời khóa biểu', '', '', NOW(), NOW()),
(7, '', 'タイトル', '', 'Tiêu đề', '', '', NOW(), NOW()),
(7, '', 'テーマ', '', 'Chủ đề', '', '', NOW(), NOW()),
(7, '', 'ストーリー', '', 'Câu chuyện', '', '', NOW(), NOW()),
(7, '', 'ヒット', '', 'Thành công, đỉnh cao', '', '', NOW(), NOW()),
(7, '', 'ブランド', '', 'Nhãn hiệu, thương hiệu', '', '', NOW(), NOW()),
(7, '', 'レンタル', '', 'Thuê', '', '', NOW(), NOW()),
(7, '', 'リサイクル', '', 'Tái chế', '', '', NOW(), NOW()),
(7, '', 'ラベル', '', 'Nhãn mác', '', '', NOW(), NOW()),
(7, '', 'タイプ', '', 'Loại, kiểu', '', '', NOW(), NOW()),
(7, '', 'スタイル', '', 'Phong cách, vóc dáng', '', '', NOW(), NOW()),
(7, '', 'セット', '', 'Bộ, set', '', '', NOW(), NOW()),
(7, '', 'ウイルス', '', 'Virus', '', '', NOW(), NOW()),
(7, '', 'ロボット', '', 'Robot', '', '', NOW(), NOW()),
(7, '', 'エネルギー', '', 'Năng lượng', '', '', NOW(), NOW()),
(7, '', 'デジタル', '', 'Kỹ thuật số', '', '', NOW(), NOW()),
(7, '', 'マイク', '', 'Micro', '', '', NOW(), NOW()),
(7, '', 'ブレーキ', '', 'Phanh xe', '', '', NOW(), NOW()),
(7, '', 'ペンキ', '', 'Sơn', '', '', NOW(), NOW()),
(7, '炊ける', 'たける', '', 'Nấu chín', 'Xuy', '', NOW(), NOW()),
(7, '炊く', 'たく', '', 'Nấu (cơm)', 'Xuy', '', NOW(), NOW()),
(7, '煮える', 'にえる', '', 'Chín, được ninh nhừ', 'Chử', '', NOW(), NOW()),
(7, '煮る', 'にる', '', 'Nấu, ninh', 'Chử', '', NOW(), NOW()),
(7, '炒める', 'いためる', '', 'Xào', 'Sao', '', NOW(), NOW()),
(7, '焼ける', 'やける', '', 'Được nướng, bị cháy nắng', 'Thiêu', '', NOW(), NOW()),
(7, '焼く', 'やく', '', 'Nướng', 'Thiêu', '', NOW(), NOW()),
(7, 'ゆでる', 'ゆでる', '', 'Luộc', '', '', NOW(), NOW()),
(7, '揚げる', 'あげる', '', 'Rán, chiên ngập dầu', 'Dương', '', NOW(), NOW()),
(7, '蒸す', 'むす', '', 'Hấp', 'Chưng', '', NOW(), NOW()),
(7, '', 'ぐっすり', '', '(Ngủ) say tít', '', '', NOW(), NOW()),
(7, '', 'きちんと', '', 'Cẩn thận, gọn gàng, ngay ngắn', '', '', NOW(), NOW()),
(7, '', 'しっかり', '', 'Chắc chắn, vững vàng, đáng tin', '', '', NOW(), NOW()),
(7, '', 'はっきり', '', 'Rõ ràng', '', '', NOW(), NOW()),
(7, '', 'じっと', '', 'Nhìn chằm chằm, đứng yên', '', '', NOW(), NOW()),
(7, '', 'そっと', '', 'Nhẹ nhàng, lén lút', '', '', NOW(), NOW()),
(7, '別々', 'べつべつ', '', 'Riêng biệt, để riêng', 'Biệt', '', NOW(), NOW()),
(7, 'それぞれ', 'それぞれ', '', 'Từng cái, mỗi', '', '', NOW(), NOW()),
(7, '互いに', 'たがいに', '', 'Lẫn nhau', 'Hỗ', '', NOW(), NOW()),
(7, '直接', 'ちょくせつ', '', 'Trực tiếp', 'Trực Tiếp', '', NOW(), NOW()),
(7, '本当に', 'ほんとうに', '', 'Thật sự', 'Bản Đương', '', NOW(), NOW()),
(7, '必ず', 'かならず', '', 'Chắc chắn, nhất định', 'Tất', '', NOW(), NOW()),
(7, '絶対に', 'ぜったいに', '', 'Tuyệt đối', 'Tuyệt Đối', '', NOW(), NOW()),
(7, '特に', 'とくに', '', 'Đặc biệt là', 'Đặc', '', NOW(), NOW()),
(7, 'ただ', 'ただ', '', 'Chỉ là, vỏn vẹn', '', '', NOW(), NOW()),
(7, '少なくとも', 'すくなくとも', '', 'Ít nhất là', 'Thiểu', '', NOW(), NOW()),
(7, '決して', 'けっして', '', 'Tuyệt đối không', 'Quyết', '', NOW(), NOW()),
(7, '少しも', 'すこしも', '', 'Một chút cũng không', 'Tiểu', '', NOW(), NOW()),
(7, '', 'ちっとも', '', 'Một chút cũng không', '', '', NOW(), NOW()),
(7, '全く', 'まったく', '', 'Hoàn toàn', 'Toàn', '', NOW(), NOW()),
(7, '', 'とても', '', 'Rất', '', '', NOW(), NOW()),
(7, '', 'どんなに', '', 'Dẫu có như thế nào', '', '', NOW(), NOW()),
(7, '', 'どうしても', '', 'Bằng mọi giá, thế nào cũng', '', '', NOW(), NOW()),
(7, '', 'まるで', '', 'Hệt như', '', '', NOW(), NOW()),
(7, '一体', 'いったい', '', 'Rốt cuộc là', 'Nhất Thể', '', NOW(), NOW()),
(7, '別に', 'べつに', '', 'Không có gì đặc biệt', 'Biệt', '', NOW(), NOW()),
(7, '', 'たった', '', 'Chỉ, vỏn vẹn', '', '', NOW(), NOW()),
(7, '', 'ほんの', '', 'Chỉ là một chút', '', '', NOW(), NOW()),
(7, '', 'それで', '', 'Do đó', '', '', NOW(), NOW()),
(7, '', 'そこで', '', 'Do vậy, vì thế', '', '', NOW(), NOW()),
(7, '', 'そのうえ', '', 'Thêm vào đó, hơn nữa', '', '', NOW(), NOW()),
(7, '', 'また', '', 'Lại, và', '', '', NOW(), NOW()),
(7, '', 'または', '', 'Hoặc là', '', '', NOW(), NOW()),
(7, '', 'それとも', '', 'Hay là', '', '', NOW(), NOW()),
(7, '', 'つまり', '', 'Tóm lại', '', '', NOW(), NOW()),

-- Unit 8
(8, '人物', 'じんぶつ', '', 'Nhân vật', 'Nhân Vật', '', NOW(), NOW()),
(8, '者', 'もの', '', 'Người', 'Giả', '', NOW(), NOW()),
(8, '各自', 'かくじ', '', 'Mỗi người', 'Các Tự', '', NOW(), NOW()),
(8, '気分', 'きぶん', '', 'Tâm trạng, cảm giác', 'Khí Phân', '', NOW(), NOW()),
(8, '気配', 'けはい', '', 'Cảm giác, linh cảm', 'Khí Phối', '', NOW(), NOW()),
(8, '生きがい', 'いきがい', '', 'Lẽ sống, ý nghĩa sống', 'Sinh', '', NOW(), NOW()),
(8, '行儀', 'ぎょうぎ', '', 'Cách cư xử', 'Hành Nghi', '', NOW(), NOW()),
(8, '品', 'ひん', '', 'Phẩm chất, phong độ', 'Phẩm', '', NOW(), NOW()),
(8, '姿', 'すがた', '', 'Bóng dáng, vẻ bề ngoài', 'Tư', '', NOW(), NOW()),
(8, '姿勢', 'しせい', '', 'Tư thế, dáng điệu', 'Tư Thế', '', NOW(), NOW()),
(8, '見かけ', 'みかけ', '', 'Vẻ bề ngoài', 'Kiến', '', NOW(), NOW()),
(8, 'ふり', 'ふり', '', 'Giả vờ', '', '', NOW(), NOW()),
(8, '苦情', 'くじょう', '', 'Than phiền, phàn nàn', 'Khổ Tình', '', NOW(), NOW()),
(8, '口実', 'こうじつ', '', 'Viện cớ, lý do', 'Khẩu Thực', '', NOW(), NOW()),
(8, '動機', 'どうき', '', 'Động cơ (hành động)', 'Động Cơ', '', NOW(), NOW()),
(8, '皮肉', 'ひにく', '', 'Mỉa mai, châm biếm', 'Bì Nhục', '', NOW(), NOW()),
(8, '意義', 'いぎ', '', 'Ý nghĩa', 'Ý Nghĩa', '', NOW(), NOW()),
(8, '主義', 'しゅぎ', '', 'Chủ nghĩa', 'Chủ Nghĩa', '', NOW(), NOW()),
(8, '精神', 'せいしん', '', 'Tinh thần', 'Tinh Thần', '', NOW(), NOW()),
(8, '年代', 'ねんだい', '', 'Niên đại, năm tháng', 'Niên Đại', '', NOW(), NOW()),
(8, '世代', 'せだい', '', 'Thế hệ', 'Thế Hệ', '', NOW(), NOW()),
(8, '基礎', 'きそ', '', 'Cơ sở, nền tảng', 'Cơ Sở', '', NOW(), NOW()),
(8, '基準', 'きじゅん', '', 'Tiêu chuẩn', 'Cơ Chuẩn', '', NOW(), NOW()),
(8, '標準', 'ひょうじゅん', '', 'Tiêu chuẩn (chuẩn mực)', 'Tiêu Chuẩn', '', NOW(), NOW()),
(8, '典型', 'てんけい', '', 'Điển hình', 'Điển Hình', '', NOW(), NOW()),
(8, '方言', 'ほうげん', '', 'Tiếng địa phương', 'Phương Ngôn', '', NOW(), NOW()),
(8, '分布', 'ぶんぷ', '', 'Phân bố', 'Phân Bố', '', NOW(), NOW()),
(8, '発展', 'はってん', '', 'Phát triển', 'Phát Triển', '', NOW(), NOW()),
(8, '文明', 'ぶんめい', '', 'Văn minh', 'Văn Minh', '', NOW(), NOW()),
(8, '普及', 'ふきゅう', '', 'Phổ cập, phổ biến', 'Phổ Cập', '', NOW(), NOW()),
(8, '制限', 'せいげん', '', 'Hạn chế', 'Chế Hạn', '', NOW(), NOW()),
(8, '限度', 'げんど', '', 'Mức độ giới hạn', 'Hạn Độ', '', NOW(), NOW()),
(8, '限界', 'げんかい', '', 'Ranh giới, giới hạn', 'Hạn Giới', '', NOW(), NOW()),
(8, '検討', 'けんとう', '', 'Thảo luận, xem xét', 'Kiểm Thảo', '', NOW(), NOW()),
(8, '選択', 'せんたく', '', 'Lựa chọn', 'Tuyển Trạch', '', NOW(), NOW()),
(8, '考慮', 'こうりょ', '', 'Xem xét, suy tính', 'Khảo Lự', '', NOW(), NOW()),
(8, '重視', 'じゅうし', '', 'Coi trọng', 'Trọng Thị', '', NOW(), NOW()),
(8, '見当', 'けんとう', '', 'Ước lượng, phỏng đoán', 'Kiến Đương', '', NOW(), NOW()),
(8, '訂正', 'ていせい', '', 'Đính chính', 'Đính Chính', '', NOW(), NOW()),
(8, '修正', 'しゅうせい', '', 'Sửa chữa (bài vở, dự án)', 'Tu Chính', '', NOW(), NOW()),
(8, '反抗', 'はんこう', '', 'Phản kháng', 'Phản Kháng', '', NOW(), NOW()),
(8, '抵抗', 'ていこう', '', 'Đề kháng, chống cự', 'Đề Kháng', '', NOW(), NOW()),
(8, '災難', 'さいなん', '', 'Rủi ro, đen đủi', 'Tai Nạn', '', NOW(), NOW()),
(8, '汚染', 'おせん', '', 'Ô nhiễm', 'Ô Nhiễm', '', NOW(), NOW()),
(8, '害', 'がい', '', 'Có hại', 'Hại', '', NOW(), NOW()),
(8, '伝染', 'でんせん', '', 'Truyền nhiễm, lây lan', 'Truyền Nhiễm', '', NOW(), NOW()),
(8, '対策', 'たいさく', '', 'Biện pháp, đối sách', 'Đối Sách', '', NOW(), NOW()),
(8, '処置', 'しょち', '', 'Xử trí, sơ cứu', 'Xử Trí', '', NOW(), NOW()),
(8, '処分', 'しょぶん', '', 'Vứt đi, xử phạt', 'Xử Phân', '', NOW(), NOW()),
(8, '処理', 'しょり', '', 'Xử lý', 'Xử Lý', '', NOW(), NOW()),
(8, '輪', 'わ', '', 'Vòng, bánh xe', 'Luân', '', NOW(), NOW()),
(8, 'でこぼこ', 'でこぼこ', '', 'Lồi lõm', '', '', NOW(), NOW()),
(8, '跡', 'あと', '', 'Dấu vết', 'Tích', '', NOW(), NOW()),
(8, '手間', 'てま', '', 'Công sức, thời gian', 'Thủ Gian', '', NOW(), NOW()),
(8, '能率', 'のうりつ', '', 'Năng suất', 'Năng Suất', '', NOW(), NOW()),
(8, '性能', 'せいのう', '', 'Tính năng', 'Tính Năng', '', NOW(), NOW()),
(8, '操作', 'そうさ', '', 'Thao tác', 'Thao Tác', '', NOW(), NOW()),
(8, '発揮', 'はっき', '', 'Phát huy', 'Phát Huy', '', NOW(), NOW()),
(8, '頂点', 'ちょうてん', '', 'Đỉnh cao', 'Đỉnh Điểm', '', NOW(), NOW()),
(8, '周辺', 'しゅうへん', '', 'Xung quanh', 'Chu Biên', '', NOW(), NOW()),
(8, '現場', 'げんば', '', 'Hiện trường', 'Hiện Trường', '', NOW(), NOW()),
(8, '状況', 'じょうきょう', '', 'Tình hình, trạng thái', 'Trạng Huống', '', NOW(), NOW()),
(8, '組織', 'そしき', '', 'Tổ chức', 'Tổ Chức', '', NOW(), NOW()),
(8, '制度', 'せいど', '', 'Chế độ', 'Chế Độ', '', NOW(), NOW()),
(8, '構成', 'こうせい', '', 'Cấu thành, kết cấu', 'Cấu Thành', '', NOW(), NOW()),
(8, '形式', 'けいしき', '', 'Hình thức', 'Hình Thức', '', NOW(), NOW()),
(8, '傾向', 'けいこう', '', 'Khuynh hướng, xu hướng', 'Khuynh Hướng', '', NOW(), NOW()),
(8, '方針', 'ほうしん', '', 'Phương châm', 'Phương Châm', '', NOW(), NOW()),
(8, '徹底', 'てってい', '', 'Triệt để', 'Triệt Để', '', NOW(), NOW()),
(8, '無視', 'むし', '', 'Vô thị', 'Vô Thị', '', NOW(), NOW());


INSERT INTO vocabularies (unit_id, kanji, hiragana, romaji, meaning, sino_vietnamese, example_sentence, created_at, updated_at) VALUES 
-- Unit 9
(9, '価値', 'かち', '', 'Giá trị', 'Giá Trị', '', NOW(), NOW()),
(9, '好む', 'このむ', '', 'Thích', 'Hảo', '', NOW(), NOW()),
(9, '嫌う', 'きらう', '', 'Ghét', 'Hiềm', '', NOW(), NOW()),
(9, '願う', 'ねがう', '', 'Mong ước, yêu cầu', 'Nguyện', '', NOW(), NOW()),
(9, '甘える', 'あまえる', '', 'Làm nũng', 'Cam', '', NOW(), NOW()),
(9, '', 'かわいがる', '', 'Yêu mến, cưng chiều', '', '', NOW(), NOW()),
(9, '気付く', 'きづく', '', 'Nhận ra', 'Khí Phó', '', NOW(), NOW()),
(9, '疑う', 'うたがう', '', 'Nghi ngờ', 'Nghi', '', NOW(), NOW()),
(9, '苦しむ', 'くるしむ', '', 'Khổ sở, chịu đựng', 'Khổ', '', NOW(), NOW()),
(9, '悲しむ', 'かなしむ', '', 'Đau buồn', 'Bi', '', NOW(), NOW()),
(9, '', 'がっかりする', '', 'Thất vọng', '', '', NOW(), NOW()),
(9, '励ます', 'はげます', '', 'Động viên, khích lệ', 'Lệ', '', NOW(), NOW()),
(9, '', 'うなずく', '', 'Gật đầu', '', '', NOW(), NOW()),
(9, '張り切る', 'はりきる', '', 'Hăng hái', 'Trương Thiết', '', NOW(), NOW()),
(9, '威張る', 'いばる', '', 'Kiêu ngạo, kiêu hãnh', 'Uy Trương', '', NOW(), NOW()),
(9, '怒鳴る', 'どなる', '', 'Gào thét, quát mắng', 'Nộ Minh', '', NOW(), NOW()),
(9, '暴れる', 'あばれる', '', 'Nổi giận, quậy phá', 'Bạo', '', NOW(), NOW()),
(9, '', 'しゃがむ', '', 'Ngồi xổm', '', '', NOW(), NOW()),
(9, '', 'どく', '', 'Tránh ra', '', '', NOW(), NOW()),
(9, '', 'どける', '', 'Dời ra, đẩy ra', '', '', NOW(), NOW()),
(9, '', 'かぶる', '', 'Đội (mũ)', '', '', NOW(), NOW()),
(9, '', 'かぶせる', '', 'Phủ lên, trùm lên', '', '', NOW(), NOW()),
(9, '', 'かじる', '', 'Nhai, cắn gặm', '', '', NOW(), NOW()),
(9, '撃つ', 'うつ', '', 'Bắn', 'Kích', '', NOW(), NOW()),
(9, '漕ぐ', 'こぐ', '', 'Đạp (xe), chèo (thuyền)', 'Tảo', '', NOW(), NOW()),
(9, '敷く', 'しく', '', 'Trải ra', 'Phu', '', NOW(), NOW()),
(9, '', 'つぐ', '', 'Rót (nước, rượu)', '', '', NOW(), NOW()),
(9, '配る', 'くばる', '', 'Phân phát', 'Phối', '', NOW(), NOW()),
(9, '放る', 'ほうる', '', 'Ném, bỏ mặc', 'Phóng', '', NOW(), NOW()),
(9, '掘る', 'ほる', '', 'Đào', 'Quật', '', NOW(), NOW()),
(9, '', 'まく', '', 'Rắc, gieo (hạt)', '', '', NOW(), NOW()),
(9, '測る・計る', 'はかる', '', 'Đo đạc, cân', 'Trắc/Kế', '', NOW(), NOW()),
(9, '占う', 'うらなう', '', 'Dự đoán, bói toán', 'Chiêm', '', NOW(), NOW()),
(9, '引っ張る', 'ひっぱる', '', 'Kéo', 'Dẫn Trương', '', NOW(), NOW()),
(9, '突く', 'つく', '', 'Đâm, chọc, chống (gậy)', 'Đột', '', NOW(), NOW()),

-- Unit 10
(10, '突き当たる', 'つきあたる', '', 'Đi hết đường, va phải', 'Đột Đương', '', NOW(), NOW()),
(10, '立ち止まる', 'たちどまる', '', 'Dừng lại', 'Lập Chỉ', '', NOW(), NOW()),
(10, '近寄る', 'ちかよる', '', 'Lại gần', 'Cận Ký', '', NOW(), NOW()),
(10, '横切る', 'よこぎる', '', 'Băng qua', 'Hoành Thiết', '', NOW(), NOW()),
(10, '転ぶ', 'ころぶ', '', 'Ngã, vấp ngã', 'Chuyển', '', NOW(), NOW()),
(10, '', 'つまずく', '', 'Vấp, sẩy chân', '', '', NOW(), NOW()),
(10, '', 'ひく', '', 'Cán, chèn (xe)', '', '', NOW(), NOW()),
(10, '', 'おぼれる', '', 'Chết đuối, chìm đắm', '', '', NOW(), NOW()),
(10, '痛む', 'いたむ', '', 'Đau', 'Thống', '', NOW(), NOW()),
(10, '', 'かかる', '', 'Bị, mắc (bệnh)', '', '', NOW(), NOW()),
(10, '酔う', 'よう', '', 'Say (rượu, xe)', 'Túy', '', NOW(), NOW()),
(10, '吐く', 'はく', '', 'Thở ra, nôn', 'Thổ', '', NOW(), NOW()),
(10, '診る', 'みる', '', 'Khám bệnh', 'Chẩn', '', NOW(), NOW()),
(10, '見舞う', 'みまう', '', 'Đi thăm bệnh', 'Kiến Vũ', '', NOW(), NOW()),
(10, '勤める', 'つとめる', '', 'Làm việc (tại công ty)', 'Cần', '', NOW(), NOW()),
(10, '稼ぐ', 'かせぐ', '', 'Kiếm tiền', 'Giá', '', NOW(), NOW()),
(10, '支払う', 'しはらう', '', 'Chi trả', 'Chi Phất', '', NOW(), NOW()),
(10, '受け取る', 'うけとる', '', 'Nhận lấy', 'Thụ Thủ', '', NOW(), NOW()),
(10, '払い込む', 'はらいこむ', '', 'Nộp tiền, đóng tiền', 'Phất Vào', '', NOW(), NOW()),
(10, '払い戻す', 'はらいもどす', '', 'Hoàn trả, trả lại tiền', 'Phất Lệ', '', NOW(), NOW()),
(10, '引き出す', 'ひきだす', '', 'Rút (tiền), lấy ra', 'Dẫn Xuất', '', NOW(), NOW()),
(10, '', 'もうかる', '', 'Sinh lời, có lãi', '', '', NOW(), NOW()),
(10, '', 'もうける', '', 'Kiếm lời', '', '', NOW(), NOW()),
(10, '落ち込む', 'おちこむ', '', 'Suy sụp, giảm sút', 'Lạc Vào', '', NOW(), NOW()),
(10, '売れる', 'うれる', '', 'Bán chạy', 'Mại', '', NOW(), NOW()),
(10, '売り切れる', 'うりきれる', '', 'Bán sạch, cháy hàng', 'Mại Thiết', '', NOW(), NOW()),
(10, 'くっ付く', 'くっつく', '', 'Dính chặt, bám vào', 'Phó', '', NOW(), NOW()),
(10, 'くっ付ける', 'くっつける', '', 'Dán vào, ghép vào', 'Phó', '', NOW(), NOW()),
(10, '固まる', 'かたまる', '', 'Cứng lại, đông lại', 'Cố', '', NOW(), NOW()),
(10, '固める', 'かためる', '', 'Làm cứng, củng cố', 'Cố', '', NOW(), NOW()),
(10, '縮む', 'ちぢむ', '', 'Co lại', 'Súc', '', NOW(), NOW()),
(10, '縮まる', 'ちぢまる', '', 'Bị thu ngắn lại', 'Súc', '', NOW(), NOW()),
(10, '縮める', 'ちぢめる', '', 'Thu gọn, làm ngắn lại', 'Súc', '', NOW(), NOW()),
(10, '沈む', 'しずむ', '', 'Chìm, lặn', 'Trầm', '', NOW(), NOW()),
(10, '沈める', 'しずめる', '', 'Làm chìm', 'Trầm', '', NOW(), NOW()),

-- Unit 11
(11, 'ぶら下がる', 'ぶらさがる', '', 'Treo lủng lẳng', 'Hạ', '', NOW(), NOW()),
(11, '転がる', 'ころがる', '', 'Lăn (tự động từ)', 'Chuyển', '', NOW(), NOW()),
(11, '転がす', 'ころがす', '', 'Làm cho lăn', 'Chuyển', '', NOW(), NOW()),
(11, '傾く', 'かたむく', '', 'Nghiêng', 'Khuynh', '', NOW(), NOW()),
(11, '傾ける', 'かたむける', '', 'Làm nghiêng, dốc sức', 'Khuynh', '', NOW(), NOW()),
(11, '裏返る', 'うらがえる', '', 'Lật ngược', 'Lý Phản', '', NOW(), NOW()),
(11, '散らかる', 'ちらかる', '', 'Bừa bộn', 'Tán', '', NOW(), NOW()),
(11, '散らかす', 'ちらかす', '', 'Làm vương vãi, làm bừa bộn', 'Tán', '', NOW(), NOW()),
(11, '散らばる', 'ちらばる', '', 'Rải rác', 'Tán', '', NOW(), NOW()),
(11, '刻む', 'きざむ', '', 'Thái, khắc', 'Khắc', '', NOW(), NOW()),
(11, '挟まる', 'はさまる', '', 'Bị kẹp', 'Hiệp', '', NOW(), NOW()),
(11, '挟む', 'はさむ', '', 'Kẹp vào', 'Hiệp', '', NOW(), NOW()),
(11, '', 'つぶれる', '', 'Bị nghiền nát, phá sản', '', '', NOW(), NOW()),
(11, '', 'つぶす', '', 'Nghiền nát, giết (thời gian)', '', '', NOW(), NOW()),
(11, '', 'へこむ', '', 'Lõm, suy sụp', '', '', NOW(), NOW()),
(11, '', 'ほどける', '', 'Bị tuột ra', '', '', NOW(), NOW()),
(11, '', 'ほどく', '', 'Cởi ra, tháo ra', '', '', NOW(), NOW()),
(11, '枯れる', 'かれる', '', 'Khô héo', 'Khô', '', NOW(), NOW()),
(11, '枯らす', 'からす', '', 'Làm héo', 'Khô', '', NOW(), NOW()),
(11, '傷む', 'いたむ', '', 'Bị hỏng (thực phẩm)', 'Thương', '', NOW(), NOW()),
(11, '湿る', 'しめる', '', 'Ẩm ướt', 'Thấp', '', NOW(), NOW()),
(11, '凍る', 'こおる', '', 'Đóng băng', 'Đống', '', NOW(), NOW()),
(11, '震える', 'ふるえる', '', 'Run rẩy', 'Chấn', '', NOW(), NOW()),
(11, '輝く', 'かがやく', '', 'Tỏa sáng', 'Huy', '', NOW(), NOW()),
(11, '', 'あふれる', '', 'Tràn ngập', '', '', NOW(), NOW()),
(11, '余る', 'あまる', '', 'Thừa thãi', 'Dư', '', NOW(), NOW()),
(11, '目立つ', 'めだつ', '', 'Nổi bật', 'Mục Lập', '', NOW(), NOW()),
(11, '見下ろす', 'みおろす', '', 'Nhìn xuống', 'Kiến Hạ', '', NOW(), NOW()),
(11, '戦う・闘う', 'たたかう', '', 'Đánh nhau, chiến đấu', 'Chiến/Đấu', '', NOW(), NOW()),
(11, '敗れる', 'やぶれる', '', 'Bị đánh bại, thua', 'Bại', '', NOW(), NOW()),
(11, '逃げる', 'にげる', '', 'Trốn chạy', 'Đào', '', NOW(), NOW()),
(11, '逃がす', 'にがす', '', 'Thả đi, để xổng', 'Đào', '', NOW(), NOW()),
(11, '戻る', 'もどる', '', 'Quay lại', 'Lệ', '', NOW(), NOW()),
(11, '戻す', 'もどす', '', 'Hoàn lại, nôn mửa', 'Lệ', '', NOW(), NOW()),
(11, '', 'はまる', '', 'Khớp, kẹt, nghiện (game...)', '', '', NOW(), NOW()),

-- Unit 12
(12, '', 'はめる', '', 'Cài, đeo (nhẫn)', '', '', NOW(), NOW()),
(12, '扱う', 'あつかう', '', 'Xử lý, đối xử, buôn bán', 'Tráp', '', NOW(), NOW()),
(12, '関わる', 'かかわる', '', 'Liên quan', 'Quan', '', NOW(), NOW()),
(12, '目指す', 'めざす', '', 'Hướng đến, nhắm đến', 'Mục Chỉ', '', NOW(), NOW()),
(12, '立つ・発つ', 'たつ', '', 'Khởi hành, xuất phát', 'Lập/Phát', '', NOW(), NOW()),
(12, '迎える', 'むかえる', '', 'Đón', 'Nghênh', '', NOW(), NOW()),
(12, '持てる', 'もてる', '', 'Có sức hút, được ưa thích', 'Trì', '', NOW(), NOW()),
(12, '例える', 'たとえる', '', 'Ví von, so sánh', 'Lệ', '', NOW(), NOW()),
(12, '努める', 'つとめる', '', 'Nỗ lực, cố gắng', 'Nỗ', '', NOW(), NOW()),
(12, '務まる', 'つとまる', '', 'Đảm nhiệm được', 'Vụ', '', NOW(), NOW()),
(12, '務める', 'つとめる', '', 'Đảm nhiệm (chức vụ)', 'Vụ', '', NOW(), NOW()),
(12, '取り消す', 'とりけす', '', 'Hủy bỏ', 'Thủ Tiêu', '', NOW(), NOW()),
(12, '終える', 'おえる', '', 'Hoàn thành, kết thúc', 'Chung', '', NOW(), NOW()),
(12, '呼びかける', 'よびかける', '', 'Kêu gọi', 'Hô', '', NOW(), NOW()),
(12, '呼び出す', 'よびだす', '', 'Gọi ra, triệu tập', 'Hô Xuất', '', NOW(), NOW()),
(12, '', 'ありがたい', '', 'Biết ơn, cảm kích', '', '', NOW(), NOW()),
(12, '申し訳ない', 'もうしわけない', '', 'Thành thật xin lỗi', 'Thân Dịch', '', NOW(), NOW()),
(12, '', 'めでたい', '', 'Đáng chúc mừng, vui vẻ', '', '', NOW(), NOW()),
(12, '幸いな', 'さいわいな', '', 'Hạnh phúc, may mắn', 'Hạnh', '', NOW(), NOW()),
(12, '恋しい', 'こいしい', '', 'Nhớ nhung', 'Luyến', '', NOW(), NOW()),
(12, '懐かしい', 'なつかしい', '', 'Hoài niệm, nhớ (quê)', 'Hoài', '', NOW(), NOW()),
(12, '幼い', 'おさない', '', 'Ngây thơ, non nớt', 'Ấu', '', NOW(), NOW()),
(12, '心細い', 'こころぼそい', '', 'Cô đơn, bất an', 'Tâm Tế', '', NOW(), NOW()),
(12, '', 'かわいそうな', '', 'Tội nghiệp', '', '', NOW(), NOW()),
(12, '気の毒な', 'きのどくな', '', 'Đáng thương, tội nghiệp', 'Khí Độc', '', NOW(), NOW()),
(12, '貧しい', 'まずしい', '', 'Nghèo nàn', 'Bần', '', NOW(), NOW()),
(12, '惜しい', 'おしい', '', 'Đáng tiếc', 'Tích', '', NOW(), NOW()),
(12, '仕方がない', 'しかたがない', '', 'Không còn cách nào khác', 'Sĩ Phương', '', NOW(), NOW()),
(12, 'やむを得ない', 'やむをえない', '', 'Bất đắc dĩ, đành chịu', 'Đắc', '', NOW(), NOW()),
(12, '面倒くさい', 'めんどうくさい', '', 'Phiền phức, rắc rối', 'Diện Đảo', '', NOW(), NOW()),
(12, '', 'しつこい', '', 'Dai dẳng, lèo nhèo', '', '', NOW(), NOW()),
(12, '', 'くどい', '', 'Dài dòng, lải nhải', '', '', NOW(), NOW()),
(12, '煙い', 'けむい', '', 'Khói mù mịt', 'Yên', '', NOW(), NOW()),
(12, '邪魔な', 'じゃまな', '', 'Vướng víu, cản trở', 'Tà Ma', '', NOW(), NOW()),
(12, '', 'うるさい', '', 'Ồn ào, phiền phức', '', '', NOW(), NOW());

